apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: qa-space
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: ahashouripour/gitops:hellov1.2
